import json,hashlib,subprocess,datetime
from pathlib import Path
repo=Path('/workspace/harness-agent'); out=repo/'.ci/web-recheck-20261004'; source='b016dc3ccbb1808728617374745fae46d5c3ee87'
def src(path,lines):return {'path':path,'lines':lines}
app='apps/web/public/app.js'; server='apps/web/src/server.ts'; gw='packages/gateway/src/gateway.ts'; rpc='packages/gateway/src/rpc.ts'
rows=[
 {'control':'#new-session-btn 新建会话','kind':'backend_identity_and_local_navigation','handler':'newSession → switchSession','frontend':src(app,'85-175, 648'),'http':['GET /api/bootstrap?from=<uuid>','GET /api/events?from=<uuid> (SSE hello)','GET /api/history?from=<uuid>','GET /api/sessions'],'backend':[src(server,'202-250, 292-324')],'rpc':[],'meaning':'bootstrap只产生有效浏览器身份；首次发送才通过Gateway创建真实agent session。'},
 {'control':'.session-button 会话切换','kind':'backend_read_and_local_navigation','handler':'switchSession → connect → loadHistoryForView','frontend':src(app,'110-247, 535-571'),'http':['GET /api/events?from=<saved>','GET /api/history?from=<saved>','GET /api/sessions'],'rpc':[],'backend':[src(server,'208-250, 292-324')],'meaning':'关闭前一视图SSE/AbortController，按messageId恢复去重历史；切换不会停止后台任务。'},
 {'control':'#send-btn / Enter 发送','kind':'backend_agent_execution','handler':'sendMessage → postJson','frontend':src(app,'574-610, 649, 655-661'),'http':['POST /api/messages {from,text}'],'backend':[src(server,'254-270, 416-443'),src(gw,'112-188, 191-213')],'rpc':['session.create (unknown sender)','session.send','session.run','session.followup (busy session)'],'meaning':'真实Harness actor运行模型/工具/验收；已有运行回合时发送的是排队的新回合。HTTP200为接收，不代表任务最终成功。'},
 {'control':'#cancel-btn 停止','kind':'backend_agent_cancellation','handler':'cancel → postJson','frontend':src(app,'260-264, 612-623, 650'),'http':['POST /api/commands {from,text:"cancel"}'],'backend':[src(server,'273-289'),src(gw,'249-267'),src(rpc,'161-171')],'rpc':['session.cancel'],'meaning':'b016主直接回合可取消；排队followup运行时仍传旧turnId的缺陷已真实浏览器复现，修复验收待补。'},
 {'control':'.allow-btn 允许执行','kind':'backend_tool_approval','handler':'showApproval.decide("allow")','frontend':src(app,'382-436'),'http':['POST /api/commands {from:ownerFrom,text:"approve:<approvalId>:allow"}'],'backend':[src(server,'273-289'),src(gw,'216-247')],'rpc':['session.approve'],'meaning':'使用审批创建时会话身份；后端校验审批属于绑定sender session，沿ApprovalStore/PermissionEngine/ToolOrchestrator执行。过期、历史审批按钮禁用。'},
 {'control':'.deny-btn 拒绝','kind':'backend_tool_approval','handler':'showApproval.decide("deny")','frontend':src(app,'382-436'),'http':['POST /api/commands {from:ownerFrom,text:"approve:<approvalId>:deny"}'],'backend':[src(server,'273-289'),src(gw,'216-247')],'rpc':['session.approve'],'meaning':'真实拒绝审批，后端记录decision及human.approval；不会执行被拒工具。'},
 {'control':'#theme-toggle 浅/深色','kind':'local_only','handler':'setTheme','frontend':src(app,'630-642'),'http':[],'rpc':[],'meaning':'data-ds-dark-theme/colorScheme + localStorage主题偏好。'},
 {'control':'#sidebar-toggle 展开/收起','kind':'local_only','handler':'setSidebar','frontend':src(app,'624-629, 643'),'http':[],'rpc':[],'meaning':'切换sidebar-collapsed，桌面偏好存localStorage；不需要后端。'},
 {'control':'#sidebar-close 收起','kind':'local_only','handler':'setSidebar(true,true)','frontend':src(app,'624-629, 644'),'http':[],'rpc':[],'meaning':'桌面收起/手机关闭drawer。'},
 {'control':'#sidebar-backdrop 遮罩关闭','kind':'local_only','handler':'setSidebar(true)','frontend':src(app,'624-629, 645'),'http':[],'rpc':[],'meaning':'手机drawer点击背景关闭；不需要后端。'},
 {'control':'.copy-button 复制回复','kind':'local_only','handler':'copyButton("复制回复") → navigator.clipboard.writeText(entry.text)','frontend':src(app,'311-324, 346-361'),'http':[],'rpc':[],'meaning':'写浏览器剪贴板；localhost/HTTPS等安全上下文及clipboard权限由浏览器控制，失败显示复制失败。'},
 {'control':'.copy-button 复制代码','kind':'local_only','handler':'copyButton("复制代码") → navigator.clipboard.writeText(code)','frontend':src(app,'311-324, 327-345'),'http':[],'rpc':[],'meaning':'仅复制围栏代码正文，模型内容按文字安全渲染。'},
 {'control':'.copy-button 重新编辑（发送失败）','kind':'local_only','handler':'sendMessage retry click','frontend':src(app,'591-605'),'http':[],'rpc':[],'meaning':'把失败消息恢复到输入框/会话草稿并聚焦；再次发送才请求后端。'},
 {'control':'Shift+Enter','kind':'local_only','handler':'input keydown keeps native newline','frontend':src(app,'655-660'),'http':[],'rpc':[],'meaning':'保留textarea换行，禁止此组合触发sendMessage。'},
 {'control':'中文IME候选确认 Enter','kind':'local_only','handler':'compositionstart/end + isComposing/keyCode229 guard','frontend':src(app,'652-660'),'http':[],'rpc':[],'meaning':'组合输入不发送；结束后正常Enter才发送。'},
 {'control':'Escape（手机）','kind':'local_only','handler':'document keydown → setSidebar(true)','frontend':src(app,'647'),'http':[],'rpc':[],'meaning':'关闭手机drawer，桌面Escape没有额外功能。'},
 {'control':'#input 编辑消息','kind':'local_only','handler':'saveDraft + resizeInput + updateControls','frontend':src(app,'70-75, 260-268, 661'),'http':[],'rpc':[],'meaning':'按会话保存浏览器草稿，空文本/历史加载中/同会话POST中禁止发送。'}]
paths=['apps/web/public/index.html',app,server,'apps/web/src/main.ts','apps/web/src/bindings.ts',gw,rpc,'packages/core/src/runtime/session-actor.ts']
fingerprints={p:hashlib.sha256(subprocess.check_output(['git','show',source+':'+p],cwd=repo)).hexdigest() for p in paths}
data={'schemaVersion':1,'auditedSourceSha':source,'auditedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'AUDIT_DEFECT_PENDING_FIX','method':'源码逐一追踪全部静态/动态按钮和快捷键；queued followup stop另用真实Chromium+productionHarness+Gateway+WebServer复现；模型为显式离线scripted provider。','staticButtonCount':7,'dynamicButtonFamilies':6,'unboundVisibleButtons':[],'mapping':rows,'absentControls':['模型切换','API key/endpoint设置','文件上传','会话删除/重命名','重新生成回复','steer专用入口'],'notes':['不存在的设置/模型按钮没有虚假事件处理；provider/model来自服务启动环境配置。','手机hero capabilities代码任务/可控执行/结果验收为非交互span标签。','会话列表来自浏览器localStorage（最多50）并用后端补标题，未实现跨浏览器帐号会话同步。','进程内from→session绑定重启不恢复，服务重启旧标签不会自动找回durable session；同一服务进程浏览器刷新可恢复。','SSE传运行/工具/审批/验收事件及完整assistant消息，生产后端未实现逐token回复显示。','HTTP接收成功应结合turn.completed/cancelled/failed和持久事件判定；未做付费模型质量测评。'],'findings':[{'id':'WEB-FOLLOWUP-STOP-1','severity':'high','status':'CONFIRMED_BUG_ON_B016DC3','trigger':'当前回合运行时发送followup；首回合完成、自动followup正在运行时点击停止','cause':'Gateway lastTurnBySession仅在直接session.send更新；自动followup使用新turnId，cancel仍引用旧id，actor返回not_running。','rawEvidence':['queued-stop-reproducer/result.json','queued-stop-reproducer/snapshot-before-stop.json','queued-stop-reproducer/snapshot-after-stop.json','queued-stop-reproducer/after-stop.png','queued-stop-reproducer/integration-red-cleanup-corrected.log'],'minimalFix':'Gateway.handleCancel在绑定sender session上通过session.status读取activeTurn.turnId，再调用既有session.cancel；starting窗口保留lastTurn回退。Core/权限/沙箱不改。'}],'sourceFingerprints':fingerprints}
(out/'button-map-audit.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':data['status'],'staticButtonCount':7,'dynamicButtonFamilies':6,'totalActions':len(rows),'confirmedBug':data['findings'][0]['id']}))
