import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

/**
 * P20-3 — documentation truth verification (`agent docs:verify`, exposed as
 * `pnpm docs:verify`).
 *
 * Machine-derivable facts that appear in HANDOVER.md / CAPABILITY_MATRIX.md /
 * benchmarks/README.md are MACHINE-CHECKED here instead of trusted by eye:
 *   - benchmark case counts (on-disk suites vs README claims)
 *   - package counts (packages/ inventory vs HANDOVER claims)
 *   - CI gates (a workflow exists and actually runs test + coverage)
 *   - capability status (CAPABILITY_MATRIX.md is machine-generated by
 *     `agent audit` — has generatedAt/gitSha + the P20-2 profile view)
 *
 * Everything is read-only and fail-closed: a claim that cannot be verified is
 * reported as false with the reason (never silently skipped).
 */

export interface DocVerificationCheck {
  name: string;
  /** True when the machine-derived fact matches the documentation. */
  truthful: boolean;
  /** Why it is truthful or not (never empty). */
  reason: string;
}

export interface DocVerificationResult {
  checks: DocVerificationCheck[];
  /** False when ANY check is untruthful (fail-closed). */
  ok: boolean;
}

const SUITE_DIRS = ["regression", "holdout", "adversarial", "stress"] as const;

/** Count benchmark case directories (each case is a subdirectory). */
async function countSuiteCases(suitesRoot: string, suite: string): Promise<number> {
  let entries;
  try {
    entries = await readdir(join(suitesRoot, suite), { withFileTypes: true });
  } catch {
    return 0;
  }
  return entries.filter((e) => e.isDirectory()).length;
}

/** Parse `node ... --suite X # comment N 个用例` style claims from the README. */
function claimedSuiteCount(readme: string, suite: string): number | undefined {
  const pattern = new RegExp(`--suite ${suite}[^0-9]*?([0-9]+)`, "i");
  const match = readme.match(pattern);
  if (match === null || match === undefined) return undefined;
  return Number(match[1]);
}

async function fileContains(file: string, needles: string[]): Promise<{ exists: boolean; found: boolean[] }> {
  let content = "";
  let exists = true;
  try {
    content = await readFile(file, "utf8");
  } catch {
    exists = false;
  }
  return { exists, found: needles.map((n) => content.toLowerCase().includes(n.toLowerCase())) };
}

/**
 * P20-3 — verify machine-derivable documentation facts under `root`.
 * Fail-closed: an unreadable file or an unverifiable claim is UNtruthful.
 */
export async function verifyDocs(deps: { root: string }): Promise<DocVerificationResult> {
  const checks: DocVerificationCheck[] = [];
  const root = deps.root;
  const benchmarksRoot = join(root, "benchmarks");
  const packagesRoot = join(root, "packages");
  const workflowsRoot = join(root, ".github", "workflows");

  // ---- benchmark case counts (README claims vs on-disk suites) ----
  let readme = "";
  try {
    readme = await readFile(join(benchmarksRoot, "README.md"), "utf8");
  } catch (err) {
    // Observable (never silent): every suite claim below will fail closed,
    // and the stderr line explains the unreadable source.
    process.stderr.write(`[docs:verify] benchmarks/README.md unreadable: ${err instanceof Error ? err.message : String(err)}
`);
  }
  for (const suite of SUITE_DIRS) {
    const actual = await countSuiteCases(benchmarksRoot, suite);
    const claimed = claimedSuiteCount(readme, suite);
    const truthful = claimed !== undefined && actual === claimed;
    checks.push({
      name: `benchmark suite: ${suite}`,
      truthful,
      reason:
        truthful
          ? `${actual} case(s) on disk matches README claim ${claimed}`
          : claimed === undefined
            ? `README does not claim a case count for ${suite} (actual on-disk: ${actual})`
            : `README claims ${claimed} for ${suite} but ${actual} case(s) are on disk`,
    });
  }

  // ---- package count integrity (packages/ inventory vs HANDOVER claim) ----
  // P20-3: the HANDOVER doc carries a claimed package count (`packages/（N 个包）`).
  // Machine truth = the claim must equal the number of packages/ members that
  // carry their own package.json. An absent claim or an unreadable HANDOVER.md
  // fails closed (never silently skipped).
  let handover = "";
  try {
    handover = await readFile(join(root, "HANDOVER.md"), "utf8");
  } catch (err) {
    process.stderr.write(`[docs:verify] HANDOVER.md unreadable: ${err instanceof Error ? err.message : String(err)}
`);
  }
  const handoverClaim = handover.match(/packages\/\s*（?(\d+)\s*个包/);
  const claimedPackages = handoverClaim === null ? undefined : Number(handoverClaim[1]);

  let actualPackages = 0;
  try {
    const entries = await readdir(packagesRoot, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      const hasPackageJson = await readFile(join(packagesRoot, e.name, "package.json"), "utf8")
        .then(() => true)
        .catch(() => false);
      if (hasPackageJson) actualPackages += 1;
    }
  } catch {
    actualPackages = 0;
  }

  const packageCountTruthful = claimedPackages !== undefined && claimedPackages === actualPackages;
  checks.push({
    name: "package count",
    truthful: packageCountTruthful,
    reason: packageCountTruthful
      ? `${actualPackages} packages/ on disk matches the HANDOVER claim ${claimedPackages}`
      : claimedPackages === undefined
        ? `HANDOVER.md does not claim a package count (packages/ on disk: ${actualPackages})`
        : `HANDOVER claims ${claimedPackages} packages but ${actualPackages} are on disk`,
  });

  // ---- CI gates: a workflow exists AND runs test + coverage ----
  const ci = await fileContains(join(workflowsRoot, "ci.yml"), ["test", "coverage"]);
  checks.push({
    name: "CI gates",
    truthful: ci.exists && ci.found.every((f) => f),
    reason: !ci.exists
      ? ".github/workflows/ci.yml is missing"
      : ci.found[0] && ci.found[1]
        ? ".github/workflows/ci.yml runs test and coverage"
        : `.github/workflows/ci.yml exists but misses ${
            ci.found[0] ? "" : "test "}${ci.found[1] ? "" : "coverage"}`,
  });

  // ---- P38.4-10: HANDOVER static truth — no volatile SHA/run-id in the
  // canonical static section. The canonical section is everything before the
  // "Historical / superseded" heading. A pattern like "Release SHA: <hex>",
  // "CI run <id>", "current attestation: <hex>" in that section means the
  // document embeds facts that become stale on the next commit.
  {
    const staticPart = (handover.split("## Historical / superseded")[0] ?? "");
    // "Release SHA: <hex>" pattern
    const releaseShaPattern = /Release\s+SHA\s*:\s*[0-9a-f]{6,}/i;
    // "CI run <digit>" pattern
    const ciRunPattern = /CI\s+run\s+\d{6,}/i;
    // "current attestation: <hex>" or "headSha == <hex>" as a stale claim
    const attestationPattern = /(?:current\s+attestation|headSha\s*==)\s*:?\s*[0-9a-f]{6,}/i;
    const volatileLines: string[] = [];
    for (const line of staticPart.split("\n")) {
      if (releaseShaPattern.test(line)) volatileLines.push(line.trim());
      else if (ciRunPattern.test(line)) volatileLines.push(line.trim());
      else if (attestationPattern.test(line)) volatileLines.push(line.trim());
    }
    const handoverStatic = volatileLines.length === 0;
    checks.push({
      name: "HANDOVER static truth (P38.4-10)",
      truthful: handoverStatic,
      reason: handoverStatic
        ? "HANDOVER.md canonical section contains no volatile SHA/run-id — a new commit does not make it stale"
        : `HANDOVER.md canonical section contains volatile claims that become stale on next commit: ${volatileLines.join("; ")}`,
    });
  }

  // ---- capability matrix: machine-generated by `agent audit` ----
  const matrix = await fileContains(join(root, "CAPABILITY_MATRIX.md"), [
    "generatedAt:",
    "| id | status | implemented | productionWired |",
  ]);
  checks.push({
    name: "CAPABILITY_MATRIX.md machine-generated",
    truthful: matrix.exists && matrix.found.every((f) => f),
    reason: !matrix.exists
      ? "CAPABILITY_MATRIX.md is missing — run `agent audit` to generate it"
      : matrix.found[0] && matrix.found[1]
        ? "CAPABILITY_MATRIX.md carries generatedAt + the audit records table"
        : "CAPABILITY_MATRIX.md exists but is not the machine-generated audit output",
  });

  // ---- P38.2-11 (INV-P38.2-011): a TRACKED matrix is informational only.
  // The Acceptable option keeps it in the repo but it MUST carry the
  // NOT RELEASE EVIDENCE marker — an unmarked tracked snapshot could be
  // mistaken for release attestation. Fail closed when the marker is absent.
  const matrixBanner = await fileContains(join(root, "CAPABILITY_MATRIX.md"), ["NOT RELEASE EVIDENCE"]);
  const matrixJsonMarker = await fileContains(join(root, "CAPABILITY_MATRIX.json"), ["\"releaseEvidence\": false"]);
  checks.push({
    name: "CAPABILITY_MATRIX marked informational (P38.2-11)",
    truthful: (matrixBanner.found[0] ?? false) && (matrixJsonMarker.found[0] ?? false),
    reason: matrixBanner.found[0] && matrixJsonMarker.found[0]
      ? "tracked matrix is explicitly NOT RELEASE EVIDENCE (informational snapshot)"
      : "tracked matrix lacks the NOT RELEASE EVIDENCE marker — regenerate with `agent audit` (P38.2-11)",
  });

  // ---- profile defaults (P20-2): matrix carries the profile view ----
  const matrixJson = await fileContains(join(root, "CAPABILITY_MATRIX.json"), ["byProfile"]);
  const matrixMdProfile = await fileContains(join(root, "CAPABILITY_MATRIX.md"), ["- profile:"]);
  checks.push({
    name: "capability profiles present",
    truthful: (matrixJson.found[0] ?? false) || (matrixMdProfile.found[0] ?? false),
    reason:
      matrixJson.found[0]
        ? "CAPABILITY_MATRIX.json carries the per-profile byProfile view"
        : matrixMdProfile.found[0]
          ? "CAPABILITY_MATRIX.md is annotated with the audit profile"
          : "no per-profile capability view found (regenerate with `agent audit` after P20-2)",
  });

  // ---- E2-12: evolution ledger is the single machine-truth source ----
  const { verifyEvolutionLedger } = await import("@ar/evaluation");
  let ledgerIssues: string[] = [];
  let ledgerKnown = false;
  try {
    const ledgerRaw = JSON.parse(await readFile(join(root, "docs", "evolution", "evolution-ledger.json"), "utf8"));
    const ledgerResult = await verifyEvolutionLedger(ledgerRaw, root);
    ledgerKnown = true;
    ledgerIssues = ledgerResult.issues.map((i) => `[${i.code}] ${i.detail}`);
  } catch (err) {
    ledgerIssues.push(`[MISSING_REFERENCE] evolution-ledger.json unreadable: ${err instanceof Error ? err.message : String(err)}`);
  }
  checks.push({
    name: "evolution ledger consistent (E2-12)",
    truthful: ledgerKnown && ledgerIssues.length === 0,
    reason: ledgerIssues.length === 0
      ? "evolution-ledger.json verifies: refs exist, digests match, summaries recompute, one active champion"
      : ledgerIssues.join("; "),
  });

  return {
    checks,
    ok: checks.every((c) => c.truthful),
  };
}

/** Render the verification result for CLI output. */
export function renderDocsVerification(result: DocVerificationResult): string[] {
  const lines = ["# Documentation truth verification", ""];
  for (const check of result.checks) {
    lines.push(`${check.truthful ? "PASS" : "FAIL"}  ${check.name}`);
    lines.push(`      ${check.reason}`);
  }
  lines.push("", result.ok ? "ALL CHECKS PASS" : "FAILED: machine-derivable doc facts are untruthful");
  return lines;
}
