import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

/**
 * P20-3 — documentation truth verification (`agent docs:verify`, exposed as
 * `pnpm docs:verify`).
 *
 * Machine-derivable facts that appear in HANDOVER.md / CAPABILITY_MATRIX.md /
 * benchmarks/README.md are MACHINE-CHECKED here instead of trusted by eye:
 *   - benchmark case counts (on-disk suites vs README claims)
 *   - package counts (packages/ inventory vs HANDOVER claims)
 *   - CI gates (a workflow exists and actually runs test + coverage)
 *   - capability status (CAPABILITY_MATRIX.md is machine-generated by
 *     `agent audit` — has generatedAt/gitSha + the P20-2 profile view)
 *
 * Everything is read-only and fail-closed: a claim that cannot be verified is
 * reported as false with the reason (never silently skipped).
 */

export interface DocVerificationCheck {
  name: string;
  /** True when the machine-derived fact matches the documentation. */
  truthful: boolean;
  /** Why it is truthful or not (never empty). */
  reason: string;
}

export interface DocVerificationResult {
  checks: DocVerificationCheck[];
  /** False when ANY check is untruthful (fail-closed). */
  ok: boolean;
}

const SUITE_DIRS = ["regression", "holdout", "adversarial", "stress"] as const;

/** Count benchmark case directories (each case is a subdirectory). */
async function countSuiteCases(suitesRoot: string, suite: string): Promise<number> {
  let entries;
  try {
    entries = await readdir(join(suitesRoot, suite), { withFileTypes: true });
  } catch {
    return 0;
  }
  return entries.filter((e) => e.isDirectory()).length;
}

/** Parse `node ... --suite X # comment N 个用例` style claims from the README. */
function claimedSuiteCount(readme: string, suite: string): number | undefined {
  const pattern = new RegExp(`--suite ${suite}[^0-9]*?([0-9]+)`, "i");
  const match = readme.match(pattern);
  if (match === null || match === undefined) return undefined;
  return Number(match[1]);
}

/** Extract the first "N 个包" / "N packages" claim from a doc. */
function claimedPackageCount(doc: string): number | undefined {
  const match = doc.match(/(\d+)\s*(?:个包|packages?)/);
  if (match === null || match === undefined) return undefined;
  return Number(match[1]);
}

async function dirEntryCount(dir: string): Promise<number> {
  try {
    return (await readdir(dir, { withFileTypes: true })).filter((e) => e.isDirectory()).length;
  } catch {
    return 0;
  }
}

async function fileContains(file: string, needles: string[]): Promise<{ exists: boolean; found: boolean[] }> {
  let content = "";
  let exists = true;
  try {
    content = await readFile(file, "utf8");
  } catch {
    exists = false;
  }
  return { exists, found: needles.map((n) => content.toLowerCase().includes(n.toLowerCase())) };
}

/**
 * P20-3 — verify machine-derivable documentation facts under `root`.
 * Fail-closed: an unreadable file or an unverifiable claim is UNtruthful.
 */
export async function verifyDocs(deps: { root: string }): Promise<DocVerificationResult> {
  const checks: DocVerificationCheck[] = [];
  const root = deps.root;
  const benchmarksRoot = join(root, "benchmarks");
  const packagesRoot = join(root, "packages");
  const workflowsRoot = join(root, ".github", "workflows");

  // ---- benchmark case counts (README claims vs on-disk suites) ----
  let readme = "";
  try {
    readme = await readFile(join(benchmarksRoot, "README.md"), "utf8");
  } catch (err) {
    // Observable (never silent): every suite claim below will fail closed,
    // and the stderr line explains the unreadable source.
    process.stderr.write(`[docs:verify] benchmarks/README.md unreadable: ${err instanceof Error ? err.message : String(err)}
`);
  }
  for (const suite of SUITE_DIRS) {
    const actual = await countSuiteCases(benchmarksRoot, suite);
    const claimed = claimedSuiteCount(readme, suite);
    const truthful = claimed !== undefined && actual === claimed;
    checks.push({
      name: `benchmark suite: ${suite}`,
      truthful,
      reason:
        truthful
          ? `${actual} case(s) on disk matches README claim ${claimed}`
          : claimed === undefined
            ? `README does not claim a case count for ${suite} (actual on-disk: ${actual})`
            : `README claims ${claimed} for ${suite} but ${actual} case(s) are on disk`,
    });
  }

  // ---- package counts (HANDOVER / docs claims vs packages/ inventory) ----
  const actualPackages = await dirEntryCount(packagesRoot);
  const docs = ["HANDOVER.md"];
  let anyDoc = "";
  for (const name of docs) {
    try {
      anyDoc = await readFile(join(root, name), "utf8");
      break;
    } catch (err) {
      process.stderr.write(`[docs:verify] ${name} unreadable: ${err instanceof Error ? err.message : String(err)}
`);
      continue;
    }
  }
  const claimedPackages = claimedPackageCount(anyDoc);
  const packageCountTruthful = claimedPackages !== undefined && claimedPackages === actualPackages;
  checks.push({
    name: "package count",
    truthful: packageCountTruthful,
    reason:
      claimedPackages === undefined
        ? `no machine-parseable package count claim found in ${docs.join("/")} (actual on-disk packages/: ${actualPackages})`
        : packageCountTruthful
          ? `doc claims ${claimedPackages} packages; ${actualPackages} on disk`
          : `doc claims ${claimedPackages} packages but ${actualPackages} are on disk`,
  });

  // ---- CI gates: a workflow exists AND runs test + coverage ----
  const ci = await fileContains(join(workflowsRoot, "ci.yml"), ["test", "coverage"]);
  checks.push({
    name: "CI gates",
    truthful: ci.exists && ci.found.every((f) => f),
    reason: !ci.exists
      ? ".github/workflows/ci.yml is missing"
      : ci.found[0] && ci.found[1]
        ? ".github/workflows/ci.yml runs test and coverage"
        : `.github/workflows/ci.yml exists but misses ${
            ci.found[0] ? "" : "test "}${ci.found[1] ? "" : "coverage"}`,
  });

  // ---- capability matrix: machine-generated by `agent audit` ----
  const matrix = await fileContains(join(root, "CAPABILITY_MATRIX.md"), [
    "generatedAt:",
    "| id | status | implemented | productionWired |",
  ]);
  checks.push({
    name: "CAPABILITY_MATRIX.md machine-generated",
    truthful: matrix.exists && matrix.found.every((f) => f),
    reason: !matrix.exists
      ? "CAPABILITY_MATRIX.md is missing — run `agent audit` to generate it"
      : matrix.found[0] && matrix.found[1]
        ? "CAPABILITY_MATRIX.md carries generatedAt + the audit records table"
        : "CAPABILITY_MATRIX.md exists but is not the machine-generated audit output",
  });

  // ---- profile defaults (P20-2): matrix carries the profile view ----
  const matrixJson = await fileContains(join(root, "CAPABILITY_MATRIX.json"), ["byProfile"]);
  const matrixMdProfile = await fileContains(join(root, "CAPABILITY_MATRIX.md"), ["- profile:"]);
  checks.push({
    name: "capability profiles present",
    truthful: (matrixJson.found[0] ?? false) || (matrixMdProfile.found[0] ?? false),
    reason:
      matrixJson.found[0]
        ? "CAPABILITY_MATRIX.json carries the per-profile byProfile view"
        : matrixMdProfile.found[0]
          ? "CAPABILITY_MATRIX.md is annotated with the audit profile"
          : "no per-profile capability view found (regenerate with `agent audit` after P20-2)",
  });

  return {
    checks,
    ok: checks.every((c) => c.truthful),
  };
}

/** Render the verification result for CLI output. */
export function renderDocsVerification(result: DocVerificationResult): string[] {
  const lines = ["# Documentation truth verification", ""];
  for (const check of result.checks) {
    lines.push(`${check.truthful ? "PASS" : "FAIL"}  ${check.name}`);
    lines.push(`      ${check.reason}`);
  }
  lines.push("", result.ok ? "ALL CHECKS PASS" : "FAILED: machine-derivable doc facts are untruthful");
  return lines;
}
