/**
 * E4-R46 (K01 follow-up) — cross-process & repeated-capture NON-overwrite.
 *
 * R40 allocated each diagnostic bundle's directory from a MODULE-LEVEL counter
 * (`ATTEMPT_SEQ`) whose value restarts at 1 in every process. In CI the
 * `verify` matrix runs many test files in separate workers that all share the
 * same `E4_09_DIAG_DIR` (`.ci/diagnostics`) and the same
 * `E2E_OBSERVATION_RUN_ID` (e4-r24-<os>-<run_id>); two failing files with the
 * same label would both compute `<label>__<os>__<runId>__attempt-1`, and the
 * recursive `mkdir` + `writeFile` would let the second OVERWRITE the first.
 *
 * The fix allocates the directory ATOMICALLY (`mkdtemp`) and carries a
 * `captureIdentity` (pid-timestamp-ordinal) INSIDE the bundle instead of
 * deriving uniqueness from the per-process counter. This test proves it across
 * two REAL independent processes (not two recorders in one process — that was
 * the old, weaker `r1.attempt !== r2.attempt` assertion):
 *
 *   - two subprocesses, SAME diag root + runId + label, write DIFFERENT marker
 *     contents;
 *   - the parent sees TWO distinct bundle directories under the shared root;
 *   - each bundle carries its OWN content and a distinct `captureIdentity`;
 *   - the SECOND capture leaves the FIRST bundle byte-for-byte intact.
 *
 * The fixture is generated by the parent (the R24/R34 pattern) into
 * `test-infra/diagnostic-fixtures/` (outside root vitest `include` and outside
 * `apps/cli` tsc `include`), run through its dedicated config, and deleted in a
 * `finally` block so an interrupted cleanup can never leak into the full suite.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { spawn } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(fileURLToPath(new URL("../../..", import.meta.url)));
const FIXTURE_DIR_REL = "apps/cli/test-infra/diagnostic-fixtures";
const FIXTURE_DIR = join(REPO_ROOT, "apps", "cli", "test-infra", "diagnostic-fixtures");
const FIXTURE_CONFIG = "apps/cli/test-infra/diagnostic-vitest.config.ts";

const TEST_FILE = "apps/cli/src/e4-r46-diagnostics-noclobber.test.ts";

let diagRoot: string;
let cleanupRoots: string[] = [];

beforeAll(async () => {
  diagRoot = await mkdtemp(join(tmpdir(), "e4-r46-diag-root-"));
  cleanupRoots.push(diagRoot);
});

afterAll(async () => {
  for (const d of cleanupRoots.splice(0)) {
    await rm(d, { recursive: true, force: true }).catch(() => {});
  }
});

/** The generated fixture: writes a bundle with the marker the parent passes, in
 *  the process the parent spawns. It imports the REAL diagnostic module source
 *  by absolute path (the fixture dir is outside `src/`, so relative import is
 *  fragile; an absolute file URL is unambiguous). */
function fixtureSource(marker: string, captureKind: "error" | "decision"): string {
  const diagAbs = join(REPO_ROOT, "apps", "cli", "src", "e4-09-diagnostics.js").replace(/\\/g, "/");
  const quoted = JSON.stringify(marker);
  if (captureKind === "error") {
    return `import { it, expect } from "vitest";\n` +
      `import { E4DiagnosticRecorder } from "${diagAbs}";\n` +
      `it(${JSON.stringify(`writes marker ${marker}`)}, async () => {\n` +
      `  const rec = new E4DiagnosticRecorder({ label: "e4-r46-same", testFile: "${TEST_FILE}", testedSha: null, testName: "subprocess marker ${marker}" });\n` +
      `  const out = await rec.captureFailure({ stage: "cross-process", error: new Error("marker ${marker}") });\n` +
      `  expect(out).not.toBeNull();\n` +
      `});\n`;
  }
  // decision kind: persist a REAL file and capture it, proving two captures
  // with differently-valued decisions write two distinct bundles.
  return `import { it, expect } from "vitest";\n` +
    `import { writeFile } from "node:fs/promises";\n` +
    `import { join } from "node:path";\n` +
    `import { E4DiagnosticRecorder, summarizeDecisionArtifact } from "${diagAbs}";\n` +
    `it(${JSON.stringify(`writes decision ${marker}`)}, async () => {\n` +
    `  const root = process.env.E4_R46_TMP!;\n` +
    `  const daPath = join(root, "decision-${marker}.json");\n` +
    `  await writeFile(daPath, JSON.stringify({ decision: ${quoted}, reasonCodes: [] }), "utf8");\n` +
    `  const rec = new E4DiagnosticRecorder({ label: "e4-r46-same", testFile: "${TEST_FILE}", testedSha: null, testName: "subprocess decision ${marker}" });\n` +
    `  rec.registerArtifacts([{ role: "decision-artifact", path: daPath, summarize: summarizeDecisionArtifact }]);\n` +
    `  const out = await rec.captureFailure({ stage: "cross-process", error: new Error("decision ${marker} non-ACCEPT") });\n` +
    `  expect(out).not.toBeNull();\n` +
    `});\n`;
}

interface SubprocessResult {
  code: number | null;
  stdout: string;
  stderr: string;
}

async function runFixtureSubprocess(marker: string, captureKind: "error" | "decision", runId: string): Promise<SubprocessResult> {
  const fixtureName = `e4-r46-fixture-${process.pid}-${Date.now()}-${cryptoish()}.test.ts`;
  await mkdir(FIXTURE_DIR, { recursive: true });
  const fixturePath = join(FIXTURE_DIR, fixtureName);
  await writeFile(fixturePath, fixtureSource(marker, captureKind), "utf8");
  const tmp = await mkdtemp(join(tmpdir(), "e4-r46-scratch-"));
  cleanupRoots.push(tmp);
  try {
    return await new Promise<SubprocessResult>((resolvePromise, rejectPromise) => {
      const child = spawn(
        process.execPath,
        ["node_modules/vitest/vitest.mjs", "run", "--config", FIXTURE_CONFIG, `${FIXTURE_DIR_REL}/${fixtureName}`],
        {
          cwd: REPO_ROOT,
          env: {
            ...process.env,
            E2E_OBSERVATION_RUN_ID: runId,
            E4_09_DIAG_DIR: diagRoot,
            E4_R46_TMP: tmp,
          },
          stdio: ["ignore", "pipe", "pipe"],
        },
      );
      let stdout = "";
      let stderr = "";
      child.stdout.on("data", (d: Buffer) => { stdout += d.toString(); });
      child.stderr.on("data", (d: Buffer) => { stderr += d.toString(); });
      child.on("error", rejectPromise);
      child.on("close", (code) => resolvePromise({ code, stdout, stderr }));
    });
  } finally {
    await rm(fixturePath, { force: true }).catch(() => {});
  }
}

function cryptoish(): string {
  // No need for real crypto; a monotonic + random suffix keeps names unique.
  return `${process.hrtime.bigint().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

describe("E4-R46 diagnostic bundles never clobber across processes", () => {
  it("two independent processes with the same root+runId+label write two distinct bundles; the second leaves the first intact", async () => {
    const runId = "e4-r46-shared-run-id";
    const r1 = await runFixtureSubprocess("ACCEPT", "decision", runId);
    const r2 = await runFixtureSubprocess("REJECT", "decision", runId);
    // Both subprocesses must have passed their own test (they only write, then
    // assert their own bundle is non-null — never a by-design failure here).
    expect(r1.code, `subprocess 1 failed:\n${r1.stdout}\n${r1.stderr}`).toBe(0);
    expect(r2.code, `subprocess 2 failed:\n${r2.stdout}\n${r2.stderr}`).toBe(0);

    // Two DISTINCT bundle directories under the shared root.
    const entries = await readdir(diagRoot, { withFileTypes: true });
    const dirs = entries.filter((e) => e.isDirectory());
    expect(dirs.length).toBe(2);

    // Each bundle carries its own content and a distinct captureIdentity.
    const bundles: Array<Record<string, unknown>> = [];
    for (const d of dirs) {
      const raw = await readFile(join(diagRoot, d.name, "diagnostic.json"), "utf8");
      bundles.push(JSON.parse(raw) as Record<string, unknown>);
    }
    expect(bundles.length).toBe(2);
    expect(new Set(bundles.map((b) => b.captureIdentity)).size).toBe(2);

    // The decisions differ per process, and BOTH survived (each has its own
    // summary, the second did not overwrite the first).
    const summaryDecisions = bundles.map((b) => {
      const summary = b.summary as Record<string, Record<string, unknown> | null>;
      return summary["decision-artifact"]?.["decision"];
    });
    expect(summaryDecisions).toContain("ACCEPT");
    expect(summaryDecisions).toContain("REJECT");

    // Byte-for-byte stability: re-read each diagnostic.json now and confirm it
    // exactly matches what was read the first time (no in-place mutation).
    for (let i = 0; i < dirs.length; i += 1) {
      const again = await readFile(join(diagRoot, dirs[i]!.name, "diagnostic.json"), "utf8");
      expect(again).toBe(JSON.stringify(bundles[i], null, 2) + "\n");
    }
  }, 120_000);

  it("a single recorder's repeated captureFailure writes an INDEPENDENT bundle each time (idempotency-by-new-dir)", async () => {
    const { E4DiagnosticRecorder } = await import("./e4-09-diagnostics.js");
    const rec = new E4DiagnosticRecorder({
      label: "e4-r46-repeat", testFile: TEST_FILE, testedSha: null, testName: "repeat capture",
    });
    const b1 = await rec.captureFailure({ stage: "s1", error: new Error("first") });
    const b2 = await rec.captureFailure({ stage: "s2", error: new Error("second") });
    expect(b1).not.toBeNull();
    expect(b2).not.toBeNull();
    expect(b1!.dir).not.toBe(b2!.dir);
    // Both live on disk simultaneously; the first was never clobbered.
    const read1 = await readFile(join(b1!.dir, "diagnostic.json"), "utf8");
    const read2 = await readFile(join(b2!.dir, "diagnostic.json"), "utf8");
    expect(read1).toContain("first");
    expect(read2).toContain("second");

    // Byte-for-byte immutability: the second capture did NOT mutate the first
    // bundle file in place.
    const again1 = await readFile(join(b1!.dir, "diagnostic.json"), "utf8");
    expect(again1).toBe(read1);
  }, 30_000);

  it("ciRunAttempt reflects process.env.GITHUB_RUN_ATTEMPT when set", async () => {
    const { E4DiagnosticRecorder } = await import("./e4-09-diagnostics.js");
    const old = process.env.GITHUB_RUN_ATTEMPT;
    try {
      process.env.GITHUB_RUN_ATTEMPT = "3";
      const rec = new E4DiagnosticRecorder({
        label: "e4-r46-attempt", testFile: TEST_FILE, testedSha: null, testName: "attempt capture",
      });
      const b = await rec.captureFailure({ stage: "s", error: new Error("retry 3") });
      expect(b).not.toBeNull();
      expect(b!.bundle["ciRunAttempt"]).toBe("3");
    } finally {
      if (old === undefined) delete process.env.GITHUB_RUN_ATTEMPT;
      else process.env.GITHUB_RUN_ATTEMPT = old;
    }
  }, 30_000);
});